<?php

  module_load_include('inc', 'gl_mail', 'gl_mail.template');
  
  define('MAIL_ERROR_SOFTWARE', 0);
  define('MAIL_ERROR_USER_NOT_FOUND', 1);
  define('MAIL_ERROR_PERMISSION_DENIED', 2);
  
  /**
   * gb_maillist will look for the following:
   * 
   * a class named EmailMimeEmail that implements IMultipartMimeEmail
   * 
   * a class named EmailDispatcher that implements IEmailDispatcher
   * 
   * a class named EmailNotifier that implements IEmailNotifier
   * 
   * internal email implementation is irrelevant to gb_maillist
   * 
   * 
   * This implementation uses drupal's built in mail functionality which
   * is an extension on PHP's mail() and the contrib modules
   * MimeMail and Emogrifier.
   */
  
  class EmailMimeEmail implements IMultipartMimeEmail {
    protected $key, $tokens;
    protected $body, $headers, $attachments, $plain, $alt_body;
    public $to, $from, $subject, $reply_to;
    
    public function set_paths($to, $from, $reply_to) {
      $this->to = $to;
      $this->from = $from;
      $this->reply_to = $reply_to;
    }
        
    public function set_subject($subject) {
      $this->subject = $subject;
    }
    
    public function set_main_body($body, $plain) {
      $this->plain = $plain;
      $this->body[] = $body;
    }
    
    public function set_alt_body($alt_body) {
      $this->alt_body = $alt_body;
    }
    
    public function add_additional_body($body) {
      $this->body[] = $body;
    }
    
    public function add_header($header, $value) {
      $this->headers[$header] = $value;
    }

    public function add_attachment($filename, $filemime) {
      if (!is_readable($filename)) {
        throw new Exception("file {$path} is not accessable / readable");
      }
      
      $this->attachments[] = array(
        'filecontent' => file_get_contents($filename),
        'filename' => basename($filename),
        'filemime' => $filemime,
      );
    }
    
    public function __get($property) {
      if (property_exists($this, $property)) {
        return $this->{$property};
      }
    }
    
    public function __isset($property) {
      if (property_exists($this, $property)) {
        return isset($this->{$property});
      }
    }
    
    public function __construct($key, $tokens = NULL) {
      $this->key = $key;
      $this->tokens = $tokens;
    }
    
    public function get_headers() {
      return $this->headers;
    }
  }

  /**
   * Interface to dispatch (send) email.
   * 
   * To be implementing by the mailing engine.
   * 
   * @api
   */
  class EmailDispatcher implements IEmailDispatcher {
    public $sender, $bounces, $send;
    
    public function __construct($sender, $bounces, $send = TRUE) {
      $this->sender = $sender;
      $this->bounces = $bounces;
      // Hard override to disable sending
      if (variable_get('gl_mail_outgoing_disabled', FALSE)) {
        $this->send = FALSE;
      } else {
        $this->send = $send;
      }
    }
    
    /**
     * This method dispatches an email.
     * 
     * @param IEmail $email the email to dispatch
     * 
     * @return boolean
     */
    public function dispatch(IEmail $email) {
      $params = array();
      $params['headers'] = array();
      $params['objects'] = array('email' => $email, 'dispatcher' => $this);
      $params['tokens'] = $email->tokens;
      $lang = language_default();
      $result = drupal_mail('gl_mail', $email->key, $email->to, $lang, 
          $params, $email->from);
      return $result['result'];
    }
    
    /**
     * This method dispatches a batch (array) of emails.
     * 
     * @param array $emails an array of IEmail objects to dispatch.
     * 
     * @return an array of booleans
     */
    public function dispatch_batch(array $emails) {
      return array_map(function ($email) {
        return self::dispatch($email);
      }, $emails);
    }
  }
  
  /**
   * Implements hook_mail()
   */
  function gl_mail_mail($key, &$message, $params) {
    $objects = $params['objects'];
    if (!empty($objects)) { // This is an e-mail we're dispatching
      $dispatcher = $objects['dispatcher'];
      $email = $objects['email'];
      
      // Allow altering before we copy the data
      drupal_alter('email', $email);
      
      // Set some addtional headers
      $message['params']['headers']['Sender'] = $dispatcher->sender; 
      $message['params']['headers']['Return-Path'] = $dispatcher->bounces;
      $message['params']['headers']['Errors-To'] = $dispatcher->bounces;
      $message['params']['headers']['Reply-To'] = $email->reply_to;
      
      if (!empty($email->headers)) {
        $message['params']['headers'] = array_merge(
            $message['params']['headers'], $email->headers);
      }
      
      // Is this message plaintext only?
      if ($email->plain) {
        $message['params']['plain'] = TRUE;
      }
      
      // If set provide an alternative plaintext body
      if (!is_null($email->alt_body) && !$email->plain) {
        // plaintext body seems to override message['body'] if we're
        // sending a plain text email (message['params']['plaintext'])
        $message['params']['plaintext'] = $email->alt_body;
      }
      
      // If set provide our array of attachment descriptors
      if (!is_null($email->attachments)) {
        $message['params']['attachments'] = $email->attachments;
      }
      
      // Set email subect & body
      $message['body'] = $email->body;
      $message['subject'] = $email->subject;
      $message['send'] = $dispatcher->send;
    }
  }

  /**
   * Implements hook_mail_alter()
   */
  function gl_mail_mail_alter(&$message) {
    if (variable_get('gl_mail_logging_enabled', FALSE)) {
      watchdog('gl_mail', 'Outgoing e-mail: ' . print_r($message, TRUE)); 
    }
  }
  
  /**
   * Implements hook_permission()
   */
  function gl_mail_permission() {
    return array(
      'administer email settings' => array(
        'title' => t('Administer e-mail settings'),
      ),
    );
  }
  
  /**
   * Implemenets hook_menu()
   */
  function gl_mail_menu() {
    return array(
      'admin/config/groupanizer/email' => array(
        'title' => t('E-mail'),
        'page callback' => 'drupal_get_form',
        'page arguments' => array('gl_mail_settings_form'),
        'access arguments' => array('administer email settings'),
        'type' => MENU_NORMAL_ITEM,
      ),
    );
  }

  /** Form callback for notifications settings form */
  function gl_mail_settings_form($form, &$form_state) {
    $form = array(
      'gl_mail_outgoing_disabled' => array(
        '#type' => 'checkbox',
        '#title' => t('Disable outgoing e-mail'),
        '#description' => t('If set the discussion boards will not send mail'),
        '#default_value' => variable_get('gl_mail_outgoing_disabled'),
      ),
      'gl_mail_incoming_disabled' => array(
        '#type' => 'checkbox',
        '#title' => t('Disable incoming e-mail'),
        '#description' => t('If set the site will not receive outside mail'),
        '#default_value' => variable_get('gl_mail_incoming_disabled'),
      ),
      'gl_mail_logging_enabled' => array(
        '#type' => 'checkbox',
        '#title' => t('Enable logging'),
        '#description' => t('If set the site will log all e-mail traffic'),
        '#default_value' => variable_get('gl_mail_logging_enabled'),
      ),
    );
    
    return system_settings_form($form);
  }
  